### ISSUE TITLE
Replication - journal change sometimes serialised before entry snapshot if we run tx-schedule inline

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#1036]
**Describe the bug**
If we use inline scheduling sometimes the journal change is serialized before the entry snapshot 
This is the inline scheduling bug
https://github.com/dragonflydb/dragonfly/tree/InlineScheduling

**To Reproduce**
Run replication pytest, see master and replica data compare fail

**Comment by romange** [comment]
@adiholden  are you talking about full sync phase? is it inconsistent?

**Comment by royjacobson** [comment]
Unfortunately couldn't reproduce the issue with `replication_test.py`

**Comment by romange** [comment]
One problem (not the only one):
`SliceSnapshot::OnDbChange` assumes it's the only fiber that pushes out previous values. it
1. checks the version 
2. if the version requires serialization, updates the version first.
3. locks the mutex (the mutex is used to wait for ongoing serialization to finish at the end of the snapshotting)
4. under mutex - serializes the bucket.

If we have another fiber changing the value. it will:
1. check the version, will see the version is uptodate and skip serialization
2. will mutate the value.

Even without the replication it may create the following artifact:
1. the first fiber blocks on the mutex and have not serialized anything yet.
2. the second fiber skips serialization and mutates the values before they were written to the snapshot.

similarly with replication: 
1. the first fiber blocks on the mutex.
2. the second fiber skips the serialization and pushes journal changes that are written before the snapshot entry.

We use mutex (and thus preempt sometimes) because of the stupid barrier inside CloseRecordChannel. 
@dranikpg  do you remember whether SliceSnapshot is called from multiple threads? Specifically, I do not remember about `SaveMode::RDB` case.  In any case, we can replace the mutex with EventCount and thus ensure full atomicity and lack of preemption of the `SerializeBucket` function.

**Comment by romange** [comment]
Another preemption problem is with `ScheduleUniqueShard` that checks locks but does not grab them, calls `RunQuickie` if the keys are unlocked.
it's fine when `TxQueue` fiber is the only one that executes commands. But with InlineScheduling, we have another fiber that does it. We may have the following situation:

Fiber1: Checks the locks but , calls RunQuickie, preempts on the replication.
Fiber2: Checks the locks, sees they are free and also calls RunQuickie and now we have 2 fibers pushing into the replication stream. The second fiber may actually proceed with RecordJournal before the first one.

**Comment by dranikpg** [comment]
> @dranikpg do you remember whether SliceSnapshot is called from multiple threads? Specifically, I do not remember about SaveMode::RDB case

Its not. `SaveMode::RDB` creates multiple separate slice snapshots, see `RdbSaver::Impl::StartSnapshotting`

**Comment by royjacobson** [comment]
From my call with Adi:

We can assume that the cb_ptr_ of the transaction runs atomically in the fiber. However, the journaling callbacks may preempt and when we have multiple such callbacks it could be problematic.

A _possible_ solution would be to split the callbacks that can preempt: first we'd only `Write` the new entries to ALL the streams, and then we'd await them. This might also be a nice throughput improvement in some cases. We can also do some simple locking around the area if we want a simpler solution.
