### ISSUE TITLE
github project enhancements 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#107]
- [ ] contributing guide.
- [ ] Introduce the issue template.
      Specifically, leading people to use "Discussions" for questions, instead of using issues will simplify my triaging work.

Something else?

**Comment by ryanrussell** [comment]
Two suggestions:

#### 1. Adopt conventional commits syntax in issues/commits: https://www.conventionalcommits.org/en/v1.0.0/
Seeing `feat(thing): What happened` or `bug(whatever): Bad thing` of `docs(readme): Add whatever` helps grep faster when the list gets long.



Believe this would help keep some sanity as you go from a handful of contributors to hundreds.

#### 2. Auto-tagging PR's based on changes in a pre-commit workflow

Little script I saw at Ritchie's wonderful Polars lib: https://github.com/pola-rs/polars/blob/master/.github/labeler.yml

Leaves you with nice auto-tagging on PR's to visually see delta's

![image](https://user-images.githubusercontent.com/523300/172263687-9d5fd5c4-5d5a-4a69-aeb9-60f78c48f869.png)

**Comment by romange** [comment]
so (1) is about education (myself included). can we enforce this notion somehow?
(2) looks really great but I wonder if it's applicable to this repo, since it's mostly c++ ?

**Comment by romange** [comment]
btw, vector looks great and its documentation is fantastic.

**Comment by ryanrussell** [comment]
> so (1) is about education (myself included). can we enforce this notion somehow? 

I would tweak on this pre-commit hook gist: https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13

It looks like your issues are starting to bloom with core `DragonFly` issues; I can put this after this `docker-compose.yml` if you want to adopt conventional commits but don't have cycles.

> (2) looks really great but I wonder if it's applicable to this repo, since it's mostly c++ ?

I would apply to docs, examples, tools, tests, etc.. maybe some subfolders within src get special nested tags?

Here's the same commit hook for labels but applied to Vector(Single Lang). I personally like Ritchie's because the color coding; let's you move fast.

You can see how they have setup labels: https://github.com/vectordotdev/vector/blob/master/.github/labeler.yml

![image](https://user-images.githubusercontent.com/523300/172370151-acd36615-8f0d-4061-b9ae-c5230a5e8c38.png)

I would stackrank the `labeler` below getting the conventional commits implemented.

**Comment by romange** [comment]
I would love if you could handle this after adding docker-compose. 
I won't be able to master everything, unfortunately, so covering these areas will be a great help for the project!

**Comment by ryanrussell** [comment]
@romange 

Happy to. If you want to move the bricks and give me the feathers, that's cool.

**Comment by romange** [comment]
lol. 🤣   

did you invent this phrase!? 
Tried to look it up but did not find anything

**Comment by ryanrussell** [comment]
@romange @alisaifee 

Found two decent clang pre-commit hooks. Thoughts? Other preferences? Is this something you want in your workflow? 

This kind of thing should probably be chosen on your side... Should be easy to amend the pre-commit yaml files to add more linting if you like one of these...

https://github.com/pocc/pre-commit-hooks
https://github.com/pre-commit/mirrors-clang-format

@romange ... Going to leave the clang linting choices to you :)

**Comment by romange** [comment]
Opened #200 for formatter hook. Re PR labeling - based on the Pr volume, it's not a problem we need to solve today.
Closing this issue as completed.

**Comment by romange** [comment]
The first choice seems more capable even if we won't use all of its
features. Also, it has more stars.

I need to learn this stuff gradually myself.

I use clang-format within vscode and base my code on Google Styleguide with
some relaxations (80 chars width in 2022 borders with masochism).
But I have not used automation checks before.
