### ISSUE TITLE
XADD missing NOMKSTREAM and MINID options

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1163]
Also LIMIT option is missing

**Comment by Abhra303** [comment]
Working on the issue. @romange Could you assign it to me?

**Comment by romange** [comment]
Sure, thanks!

**Comment by Abhra303** [comment]
Hey @romange, I have implemented `NOMKSTREAM` and `MINID` for XADD. But I find that the redis "[stream.h](https://github.com/dragonflydb/dragonfly/blob/main/src/redis/stream.h)" library doesn't provide any function API that excepts "limit" value to limit the trimming of streams. Functions like [`streamTrimByID`](https://github.com/dragonflydb/dragonfly/blob/c3dc05a5719d1b755160d0df1a109978daf191ec/src/redis/t_stream.c#L896) and [`streamTrimByLength`](https://github.com/dragonflydb/dragonfly/blob/c3dc05a5719d1b755160d0df1a109978daf191ec/src/redis/t_stream.c#L885) sets the limit to a default value (which is `100 * server.stream_node_max_entries`).

The only possible way I can think is to add the declaration of [`streamTrim`](https://github.com/dragonflydb/dragonfly/blob/c3dc05a5719d1b755160d0df1a109978daf191ec/src/redis/t_stream.c#L723) function and "streamAddTrimArgs" struct to redis "stream.h" library so that I can use that function.

What is your thought on it? Is it possible to modify the "stream.h" library (i.e. according to redis license)?

**Comment by romange** [comment]
Yes, of course you can. In fact you can see our changes under src/redis.
