### ISSUE TITLE
HELLO 3 behavior breaks lettuce

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#126]
Based on private communication. Lettuce client stopped connecting to DF.

From reading this logic:
https://github.com/lettuce-io/lettuce-core/blob/5d3310d79967a580d172af7f6d9718ec9ed0325f/src/main/java/io/lettuce/core/RedisHandshake.java#L97

we should not return NOPROTO error upon "hello 3" command because the client code expects a `ERR unknown command` response.

**Comment by alisaifee** [comment]
Ouch, that's unfortunate. 

Initially when I looked at the expectation in the lettuce implementation it felt like a bit of a stretch to return the 'unknown command' family of errors. However, technically the current implementation of HELLO in df is a bit of a lie still since you could pass the authentication / set name arguments and the response would be (incorrectly) "OK". 

Given that, what do you think of:
- accept *only* no arguments or protover=2 and return `OK`
- for all other arguments return `unknown command "HELLO", with args beginning with: ...."

**Comment by romange** [comment]
you mean - return the 12-item array and not "OK", right?
I agree, I think we should support "hello [2]".  we can even support "hello 2 setname foo"  since this functionality already exists.
For all other cases - return "unknown command..."

**Comment by alisaifee** [comment]
> you mean - return the 12-item array and not "OK", right? 

Apologies, my mind said `HELLO RESPONSE` but my fingers typed 'OK' ... not enough ☕, but yes.

**Comment by alisaifee** [comment]
Resolved in #129
