### ISSUE TITLE
!BADKEY

### ISSUE THREAD

**Issue by atomotic** [dragonflydb/dragonfly#1327]
**Describe the bug**
I tried to switch from Redis to Dragonfly in a running Go application using `github.com/redis/go-redis/v9`.
[SAdd](https://pkg.go.dev/github.com/redis/go-redis/v9#Client.SAdd) returns `!BADKEY`

```
{"time":"2023-05-31T10:47:17.910311994+02:00","level":"ERROR","msg":"error","!BADKEY":"write tcp 127.0.0.1:55768->127.0.0.1:6379: write: broken pipe","ente":1}
```

**Environment (please complete the following information):**
 - OS: [ubuntu 22.04]
 - Kernel: `Linux search-6 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Containerized?: Bare Metal
 - Dragonfly Version: v1.3.0-f80afca9c23e2f30373437520a162c591eaa2005

**Reproducible Code Snippet**
```
key := fmt.Sprintf("%d:%s", h["ID"][0], query)
err := rdb.SAdd(ctx, key, h[query]...).Err()
if err != nil {
        return err
}
```

`key` is something like `1101:Maps`, `1101:Manuscripts`

**Comment by romange** [comment]
I do not think it's related to dragonfly directly. `BADKEY` is not error that is returned by either go-redis or dragonfly. 
can you write a reproducible self-contained sample that we can run ourselves?

**Comment by romange** [comment]
you can use redis-cli MONITOR to track the commands sent to both redis and dragonfly

**Comment by romange** [comment]
Any updates @atomotic ?

**Comment by romange** [comment]
Need more info to investigate. Please reopen if you have more data or a reproducible, self contained code snippet.

**Comment by atomotic** [comment]
sorry for leaving the ticket open. I'm on other activities, will be back on it next week.

**Comment by romange** [comment]
Ok, I will wait for your response then :)

**Comment by atomotic** [comment]
The following Go code with rueidis client will generate a slice of random strings (250k values) and then saves into a Set.
Works with redis, fails with dragonfly.
With smaller slices (until 30k values) it works in Dragonfly too.

```go
package main

import (
	"context"
	"math/rand"

	"github.com/redis/rueidis"
)

const letterBytes = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

func generateRandomString(length int) string {
	b := make([]byte, length)
	for i := range b {
		b[i] = letterBytes[rand.Intn(len(letterBytes))]
	}
	return string(b)
}

func main() {
	ctx := context.Background()

	size := 250000
	members := make([]string, size)

	for i := 0; i < size; i++ {
		randomString := generateRandomString(10)
		members = append(members, randomString)
	}

	r, err := rueidis.NewClient(
		rueidis.ClientOption{
			InitAddress:  []string{"100.92.106.13:6379"},
			SelectDB:     0,
			DisableCache: true})
	if err != nil {
		panic(err)
	}
	defer r.Close()

	err = r.Do(ctx, r.B().Sadd().Key("exampleset").Member(members...).Build()).Error()

	if err != nil {
		panic(err)
	}

}
```


```
panic: write tcp 100.121.183.43:58297->100.92.106.13:6379: write: broken pipe
```

with `MONITOR` I see:

```
127.0.0.1:6379> monitor
OK
1686904010.7969196 [0 100.121.183.43:58297]  "HELLO" "3"
1686904010.8257296 [0 100.121.183.43:58297]  "CLUSTER" "SLOTS"
```

**Comment by romange** [comment]
@andydunstall  any chance you will be able to look at it?

The problem is that Dragonfly rejects arrays above a certain limit (see kMaxArrayLen in redis_parser.cc). 
The thing is - I am not sure why the UX on client side is so confusing. 

1. Why "BADKEY"? I know dragonfly closes the connection when it fails to parse correctly. Maybe in this case worth draining the input and then reply with `SendError` ?
2. If not, maybe to add ERROR log in dragonfly when this happens?

It's not the first time users stumble upon this - I know Dragonfly is more restrictive in this case but we should at least make it simpler to debug the problem

**Comment by andydunstall** [comment]
> @andydunstall any chance you will be able to look at it?

Yep sure will look today

**Comment by andydunstall** [comment]
Running the above example I can't see a `BADKEY`? Just `write tcp 127.0.0.1:47630->127.0.0.1:6379: write: broken pipe`

> Maybe in this case worth draining the input and then reply with SendError ?

I'm not sure how this would work? I guess we'd still need to parse the command so we know now much data to read (to ensure the clients write succeeds), though not store the command data (or just store the data and return an error after the command has been parsed to keep simple?)? Then do you mean the connection should stay open?

Looks like DF is already sends a `ERR Protocol error: invalid multibulk length` response before the connection is closed, but the client hasn't finished writing so ends up getting an RST response and the write fails, so never reads the error response

> I know Dragonfly is more restrictive in this case 

Out of interest why is DF more restrictive?

**Comment by romange** [comment]
For reference, just opened a related  PR https://github.com/dragonflydb/dragonfly/pull/1420  though for different reasons.

The reason I would like to restrict array lengths is because it's a potential vurnerability even for non-authorized clients. Suppose you have an endpoint protected by auth. Still it respects the rules of the protocol, so potentially you can send to it huge blobs as an array which parser will have to parse before DF will respond with "unauthorized". 

For non-adversarial usecases, we want to reduce the overhead of a single request compared to the total memory usage. 
I just want to avoid uses-cases when a single request may potentially cause OOM just because it's so huge. In the future, it may become a configurable flag, I guess.

And yes, I meant draining the data because of a case when a client app is still writing to a socket when DF sends it an error. This is needed to allow easier debugging of the problem on users' side (better UX). If you have a better idea, I am open to suggestions 😄

**Comment by andydunstall** [comment]
Ok sure

Looks like Redis has a lower limit if the user is unauthenticated (though authentication is enabled) (https://github.com/redis/redis/blob/unstable/src/networking.c#L2268). Is it worth doing something similar, then the limit could be increased?

Draining the socket so we know the client has finished writing seems like a hard problem to solve unless we know how much data the clients writing? We could parse the command (without storing the result in memory), but then the client could be sending multiple commands before they do a read? Or am I missing something? (I'm happy to work on this I just want to make sure I understand it :) )

**Comment by romange** [comment]
Wow, have not expected that level of sophistication from Redis networking code. Probably there are some interesting stories behind these lines. I still do not think that having `INT_MAX` is a reasonable limit.

Regarding draining - you are right, pipelining might indeed interfere. We could also enter a special finalizing state in dragonfly_connection where we just unconditionally read from the socket as long as there is data but this is also not perfect because it could be that not all the data is sent. I think that any partial solution would be better than no solution and since we are raising the bar with error propagation, I think it's ok to have not 100% sealed solution. so any improvement that partially addresses the problem would fit here.

**Comment by andydunstall** [comment]
> dragonfly_connection where we just unconditionally read from the socket as long as there is data

Ok yep sure - something like https://github.com/dragonflydb/dragonfly/pull/1422?

**Comment by romange** [comment]
Better error handling is added
