### ISSUE TITLE
Implement Built-in Support for BullMQ API - Root task

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1406]
This is the overhaul task covering high-level requirements for the project.

Currently, Dragonfly relies on Lua scripts to handle the state management of BullMQ and other job management frameworks. However, these scripts require generating keys at runtime, which poses challenges for efficient parallelization of lua execution while maintaining atomicity.

To address this limitation, we introduce DragonQ, a project that aims to provide an alternative solution. DragonflyQ preserves the high-level semantics of the lua scripts executed by BullMQ while ensuring atomicity and enabling efficient parallelization.

DragonflyQ introduces an API that seamlessly powers each eval script from BullMQ with dedicated code. This approach allows us to implement equivalent commands that are both atomic and parallelizable, overcoming the limitations of the previous Lua script-based implementation.

**Comment by manast** [comment]
As the author of BullMQ let me give you my two cents here... re-implementing the functionality of BullMQ's lua script is far from being a trivial job to do. Furthermore, we are improving, fixing issues, and adding new features continuously, it would be quite challenging to keep the API up-to-date, not to mention if the goal is to be interoperable. I started a project some time ago (https://github.com/taskforcesh/bullmq-redis) but have since been down-prioritized because Redis modules are not very popular in practice outside of Redislab's environment
So I think that it would be wiser to invest time into either providing a generic API to write modules for Dragonfly (so that it can be used to implement new commands that may be useful for BullMQ or similar), or to just assume the Lua scripts are going to be "misused" and try to do whatever is possible to make them run as fast as possible...
