### ISSUE TITLE
Add some fields to INFO PERSISTENCE

### ISSUE THREAD

**Issue by royjacobson** [dragonflydb/dragonfly#1408]
In particular:

- `loading:0/1` for whether we're currently loading a db file
- A `rdb_changes_since_last_save` equivalent (needs to be properly defined in multi sharded context, though, and less important)

**Comment by adiholden** [comment]
@kostasrim I am copping your question to here
quick question, so, I am adding the fields described in https://github.com/dragonflydb/dragonfly/issues/1408 to INFO PERSISTENCE. I tried redis to observe the behavior of rdb_changes_since_last_save and it appears that this field is not updated on an expired value. So for example, SET key 1 EX 1 wait for 1 second and then run INFO PERSISTENCE produces a result value of 1 instead of 2(which in my opinion is wrong, because the expired value should count as an update since it's an implicit delete operation). Do we want to subscribe to the same behavior or diverge and print 2 instead of 1? 

Moreover, it seems like the most sensible thing to do is to add a counter on the DbStats and then update it each time we call PostUpdate() on that particular dbslice (and then ofc each time we snapshot we set the counter back to 0). Are there any strong objections on this?

**Comment by adiholden** [comment]
1. I think it makes sense to count the expired , though if you would load the old rdb file with the expired keys they should expire on loading, so this has no affect on persistence.
2. updating DbStats sounds good

**Comment by romange** [comment]
Expired cause deletions so if you count deletions, you will automatically count effective expired.
please note that DbStats is per database (select N) while it's suffice for you to count changes per shard thread.
in addition, you will need to reset this metric after the save event. I suggest considering `SliceEvents events_` for this as well (have not checked at depth)

**Comment by kostasrim** [comment]
@romange Thank you for pointing out `select` command, now the concept of multiple databases "namespaces" makes sense. I agree `SliceEvents` is better and I ended up adding it there. 

@adiholden Roman pointed out `delete` operations and it came to my mind that I haven't looked what happens with the field counter when we explicitly delete a key with a `del` command. Turns out redis does not count this either, so I opted in for consistency (I thought only expired values where not counted indicating a bug on redis side) and therefore I decided not to count the `expired and deleted values`. If you strongly disagree with this plz make a comment on my PR and I will address this.
