### ISSUE TITLE
Add support for SLOWLOG GET command

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#1617]

**Comment by talbii** [comment]
Unfortunately I won't get around to fully implementing this. Here is how I planned to do so:

First, some background. For SLOWLOG you need to following subcommands:

- `SLOWLOG HELP`
- `SLOWLOG LEN`    - prints the length of the log stored
- `SLOWLOG GET <N>`    - gets the last N entries
- `SLOWLOG RESET`  - clears the log

and the configs:
- `--slowlog-log-slower-than <N>`: logs commands which take more than N microseconds.
- `--slowlog-max-len <N>`: specifies the maximum limit for the log size.

which should probably also be available using CONFIG SET.

A log entry has format:

* unique id
* unix timestamp
* execution time in us
* array consisting of the command and its arguments
* client address+port
* client name, if set (via CLIENT SETNAME)

Let us store it in the structure `SlowlogData`.

Here is a possible implementation.
1. Implement SLOWLOG commands, and have them always on by default
2. Later add the configs

The duration of a command is tracked in two places:
- CommandId::Invoke() 
- Service::DispatchCommand()

so either of these places would work. I believe that it would be easier to implement in CommandId, and here is how I would do it:

- Because we need a unique ID, this would require an atomic variable... or: save IDs per shard. Let X be the number of shards, and SID the shard ID. Then each shard would have something like

[ServerState]
  thread_local int unique_id = SID; // init

- And then, when we access the unique_id for reading we also update it:
    `unique_id += X;`

- This ensures lock-free and unique IDs in the server.
- Timestamp is simple. So is execution time (we already have it).
- Args are also given to Invoke() and we can get the CID from *this.
- I believe getting client IP and address is not too problematic, I think we can extract that information from dfly::ConnContext::owner()
- The last one is client name, I did not look at how this is implemented so I cannot comment on this.

Okay, this is only how to gather data. How is SLOWLOG itself implemented?

- SLOWLOG RESET:
Schedule a tx which hops all shards and clears ServerState::SlowlogData.

- SLOWLOG LEN:
Schedule a tx which hops all shards and sums ServerState::SlowlogData::log_length().

- SLOWLOG GET:
Schedule a tx which hops all shards and gets ServerState::SlowlogData. Afterwards, sort it by the UNIX timestamp saved.

- SLOWLOG HELP:
Print a simple help message.


---

It might be difficult to support implementing the flags (specifically, the second one) as well as `SLOWLOG GET <N>` to work well with multiple shards. Maybe this is not even a hot path so a trivial implementation like a global `std::atomic<SlowlogData>` would work fine.

**Comment by UkuLoskit** [comment]
Hello! Could this issue be assigned to me? I have a partially working solution, although not everything is addressed yet. Will try to submit a PR this week.

**Comment by romange** [comment]
Sure! And in case you are planning to participate in hacktoberfest, I labelled the issue accordingly.
