### ISSUE TITLE
Add persistence via load/store

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1807]
Add:

* ACL SAVE
* ACL LOAD
* flag configuration

**Comment by romange** [comment]
how flag configuration looks like? 
lets talk about the aclfile. I suggest using yaml for that. We can integrate an yaml lib and parse/save yaml acl file with predefined schema without using all those cryptic symbols

**Comment by kostasrim** [comment]
> how flag configuration looks like?

Flag is: `--acl_file=path/filename` 

> lets talk about the aclfile. I suggest using yaml for that. We can integrate an yaml lib and parse/save yaml acl file with predefined schema without using all those cryptic symbols

There are a few things here. First, let's discuss what redis is doing:

`Redis` is basically spitting the exact layout of the command on the ACL file. So for example, if I call this:

```
ACL SETUSER kostas +@fast +@transaction
ACL SETUSER roman +@string
```

The file will look exactly like that. 

I am against using a `yaml` file for a few reasons:
1. We already can parse this logic in our `ACL SETUSER` command implementation. We do not need another format or library to parse the exact same code. We just load the file, and call our registered ACL SETUSER callback for each line. 

2. Users from redis with already existing acl configurations can move their config files without any changes (ok I am slightly lying here -- unless we add support for filtering keys which we agreed we don't care for now -- they will still need to adjust -- but incorrect files won't load since again the logic is covered in our command implementation.

3. If we find that this approach is slow, that is, loading a config file is slow, I would either use a yml or serialize (for example isntead of outputing the acl categories just output directly the uint32_t mask that represents the categories). I think this is an overkill since we only read from this file once and we only write to it explicitly via `ACL SAVE`.

**Comment by romange** [comment]
we can not change the command API but config format is a grey area. I do not like redis.conf format (and we do not support it).
Committing to config compatibility means we can not really improve the usability around it. I do accept your argument about introducing yet another language.

**Comment by romange** [comment]
performance is not a concern here

**Comment by kostasrim** [comment]
But the `config format` is different! When I am saying config format I am talking about the layout of the acl configuration file, not the `redis.conf` file. 

They are separate files, so we won't support `redis.conf` but we will support the `acl format`. Think about it as the `rdb format`, it's the same

**Comment by kostasrim** [comment]
To give you an example:

file name `users.acl`. Contents: 

```
ACL SETUSER kostas +@fast +@transaction
ACL SETUSER roman +@string
```

And then we load it line by line, feed it to the `SETUSER` command and we are done and we get a nice bonus of supporting the exact same format for migration. 

Any strong objections?

**Comment by romange** [comment]
no objections :)
