### ISSUE TITLE
Dragonfly RSS memory spikes dramatically in certain situations

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#1955]
Scenario:

master (02)/slave (01). See below the spikes. Slave was lots on a way but not sure what caused what.
Master froze for several minutes because the system uses swap disk. 
(master version - 1.6.2)
![image](https://github.com/dragonflydb/dragonfly/assets/3674760/e40fb01b-dce8-4075-b489-b70052994512)

Info log from a differrent instance (v1.10) but a similar workload.
[info.txt](https://github.com/dragonflydb/dragonfly/files/12740986/info.txt)

1. questions: what can cause huge memory spikes assuming it's not the database that grew?
2. Do we have unbounded buffers?
3. Do we cover monitor their capacities with INFO memory stats?

**Comment by dranikpg** [comment]
#### Buffers structure

Full sync:
1. Slice-snapshot records channel: max-size 128 entries, no byte limit)
2. RdbSerializer's own buffer: at most one bucket without flushing, flushing journal (max 4kb)

Stable sync:

2. buffered streamer - strictly adheres to max-size and max-bytes

---

#### Charts

- Unclear when traffic drops (commands_processed_total keeps same), should be zoomed in
- Lag chart has no y-axis, **but its enough to see that before any spike, lag always accumulates**
---

#### Hypothetical issues

1. Countless retries/reconnects before lead to memory growth, for example if retry starts before finished cleanup
  -> tried crashing single replica with 1000 * 20mb (20 gigs) keys and memory usage was not growing steadily

2. A few very large keys clogging the pipeline
  -> full sync limited to max bucket size in any case, but rdb serializer buffer never shrinks, so peak keeps till end of full sync
  -> stable sync limited to twice max value size, but never shrinks to fit

3. Pipeline request pool grows out of bounds
  -> has an upper limit of 64mb per connection (doesn't factor in self overhead)

4. Due to constant backpressure DF accumulates too many async commands
  -> we indeed _don't ensure memory budget for async commands_, but the memory increase on the chart is too steep, full sync's side save logs show qps is not high 
  -> big pipelines are often not sent blindly and old replies are awaited

(4) seems to be the only possible place for unbounded memory growth based on what I found 🤔 

---

#### Metrics

- total connection's dispatch q size and memory usage (aka lag)
- buffered streamer total buffer size
- a total retires metric for replication would be helpfull

**Comment by romange** [comment]
@dranikpg can we close this?

**Comment by dranikpg** [comment]
Have we found a cause for this?

I'm not sure because the spike is on master, we solved a bug for the replica...

**Comment by chakaz** [comment]
@romange could this have been due to huge values?
(and also - can we close this issue now?)
