### ISSUE TITLE
Set and hash field expirations are not persisted after restart

### ISSUE THREAD

**Issue by UkuLoskit** [dragonflydb/dragonfly#2052]
**Describe the bug**
When using Dragonfly-specific functionality that enables setting expiration for fields, i.e HSETEX and SADDEX, the expiration is not persisted after restarting Dragonfly.

**To Reproduce**
```
HSETEX myhash 30 foo bar

restart Dragonfly
sleep 30;
HGET myhash foo
bar  < --- field foo still exists
```

**Expected behavior**
```
HSETEX myhash 30 foo bar

restart Dragonfly
sleep 30;
HGET myhash foo
(nil)
```

**Environment (please complete the following information):**
 - Dragonfly Version: Dragonfly HEAD

**Comment by chakaz** [comment]
This bug also affects replication in (at least?) 2 ways:

1. Replica which connects _after_ a key with element expiry was set will never remove the expired element (it will simply not know about the expiration)
2. Replica which connects _before_ a key was set (i.e. that it gets the original command `HSETEX` command) will remove the items on its own, instead of waiting for expiration removal event coming from the master

**Comment by chakaz** [comment]
And fixing this is not trivial as it:
1. Will break compatibility with Redis RDB format
2. Will break compatibility with old Dragonfly replicas
3. Will break compatibility with old Dragonfly servers trying to load new RDB files

All of these can and should be resolved, but I'm trying to say that it's not an easy solution and we need to be careful here.
