### ISSUE TITLE
ConfigRegistry::Set(...) inconsistency behavior

### ISSUE THREAD

**Issue by BorysTheDev** [dragonflydb/dragonfly#2097]
function `ConfigRegistry::Set(...)` can update flag and return `SetResult::INVALID`, in the case when `cb(*flag)` returns false.

```
auto ConfigRegistry::Set(std::string_view config_name, std::string_view value) -> SetResult {
  ....
  if (!flag->ParseFrom(value, &error))
    return SetResult::INVALID;

  bool success = !cb || cb(*flag);
  return success ? SetResult::OK : SetResult::INVALID;
}
```

Also, I think we need to add  LOG(WARNING) for error.

**Comment by kostasrim** [comment]
Hi @BorysTheDev and welcome again :)

That's true but non of the callbacks registered in DF return `false` and I don't think they ever will since they just read the updated flag value. 

That being said, maybe we should be returning a value (i.e, `void`) from the callbacks at all.

**Comment by BorysTheDev** [comment]
config_registry.RegisterMutable("maxmemory", [](const absl::CommandLineFlag& flag) {
    auto res = flag.TryGet<MaxMemoryFlag>();
    if (!res)
      return false;

    max_memory_limit = res->value;
    return true;
  });

**Comment by chakaz** [comment]
We could get the serialized flag value before attempting to modify it, and then if `cb` returns failure we can rollback.

**Comment by kostasrim** [comment]
@chakaz I was skimming through the abseil flags, and I could not find a function that parses but not sets the flag. Instead of rollbacks, I would prefer the following chore:

1. Parse the flag but don't set it. Now we have the value we want to set the flag to (Similar to `ParseFrom` but on a copy)
2. Validate/verify 
3. Set and Apply the cb 

And that would not need a rollback. The only thing I found close to this, is to copy the whole registry (abseil has this utility function that basically introduces a copy of the flag registry in the scope -- and it cleans it up afterwords) but obviously I don't want to copy the whole registry to do that. Lame....

**Comment by chakaz** [comment]
> I could not find a function that parses but not sets the flag
I'm not sure what you mean by that?

**Comment by kostasrim** [comment]
@chakaz 

```
copy_of_flag = !flag->ParseFrom(value, &error)
```

So now `flag` will contain the old value and `copy_of_flag` will contain the new one. That way, after I validate and call `cb`, I can
`flag = copy_of_flag`.

That way we don;t need rollbacks as redis.

**Comment by kostasrim** [comment]
The only way is through the copy of the whole flag registry but that's meh :(
