### ISSUE TITLE
Make sure `PreUpdate()` and `PostUpdate()` are always called

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2252]
The test will run "commands" command to retrive all commands with write flag.
The test will run client tracking and for each write command will check that we get invalidation of the key touched

**Comment by chakaz** [comment]
Here's an idea:
How about instead of calling `PostUpdate()` manually, we'll only have a `PreUpdate()` call, which returns some object. This object will, upon destruction, call (a `protected`?) `PostUpdate()`. It will be `move`able, and will be passed to whatever function finishes handling the update.

Advantages:
* As long as we will call `PreUpdate()`, we will call `PostUpdate()` (we can't forget, or only call in some of the cases)
* We can keep whatever state we want, like pre-update memory size, in that object

Disadvantages:
* It will make some of the code (slightly?) harder to read, with an additional object to pass around

Bonus points if we make `DbSlice`'s API return this, like for `AddOrFind()` etc, eliminating the need for a `PreUpdate()`.

(That is not to say we shouldn't add tests, like this issue proposes)

**Comment by BorysTheDev** [comment]
@chakaz I like your Idea. @adiholden Are you OK if I implement this ticket in this way?

**Comment by romange** [comment]
I would be very careful here. Please check if it's feasible with operations like `SREM`, `LPOP` etc where the order is important and you can not rely on c++ objects destruction order. Probably it is still possible to do it, just this helper class must support explicit calls as well.

**Comment by chakaz** [comment]
Indeed, it must support some update-now method as well as, maybe, cancelling without updating.

**Comment by chakaz** [comment]
... and `stream_family.cc` doesn't have _any_ calls to `PostUpdate()`, only `PreUpdate()` once (which I think should be more?)

**Comment by adiholden** [comment]
@chakaz yes it will be hard to cover all cases with tests 
We need to call PreUpdate only for existing keys and PostUpdate for existing keys and for new keys.  calling to PostUpdate only after PreUpdate on the obj destruction , we will need to make sure we call PostUpdate if PreUpdate was not called

**Comment by chakaz** [comment]
Can't we have this logic done in the proposed object, returned from `DbSlice` API?
It can keep internally whether the object is new or not, etc.

**Comment by chakaz** [comment]
This was completed as part of the refactor. The only remaining related task is #2316
