### ISSUE TITLE
Bug UB on access invalid prime table iterator

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2276]
This bug can happen is a very rare case when source and dest key of command belong to the same bucket of dash table.
On commands that have a source and dest key ,we call dash table Find for both source and dest key. On Find we do bumpup therefore we can invalidate the iterator to the one we called Find first if both source and dest keys are on the same bucket.

**Comment by romange** [comment]
oh wow! Did you encounter this? Since both are bumped up, i guess it can only happen if they reside next to each other. 
`|s|d|` . In fact they can even reside in a different buckets. For example, `s` in its home bucket, slot 13 (last one). 
`d` is in the stack bucket, slot 0. `d` searched first, it has been promoted to home bucket, slot 13. `s` was demoted to stash bucket. `s` now is searched as well. it's been promoted back to home bucket, demoting `d` and invalidating `it_d`.

Also, the case can apply to any multi-key operation that finds multiple keys before processing them. For example,  `OpMGet` first finds all the keys in the shard and then processes them.

**Comment by chakaz** [comment]
Maybe it's a hammer looking for a nail, but will adding some checks during the destruction of `AutoUpdater` help?

https://github.com/dragonflydb/dragonfly/pull/2268

**Comment by adiholden** [comment]
@romange I did not encounter this, but while reviewing the PR of autoupdater and our flow related to tiering I just realised we have a bug here

**Comment by romange** [comment]
this bug needs to be fixed. please tell me if you are gonna look into it or should I

**Comment by adiholden** [comment]
@romange I want to suggest fixing this by using the same mechanism Shahar intruduced with AutoUpdater . We will set the items to sticky after calling db.Find() and setting the sticky back to the original value when the AutoUpdater is destructed. Because sticky items does not allow bumpdown this should fix the problem. What do you think about this solution?
