### ISSUE TITLE
Search Implementation - Query Time Sorting

### ISSUE THREAD

**Issue by claridgicus** [dragonflydb/dragonfly#2311]
**Is your feature request related to a problem? Please describe.**
When using search, on a dataset, where you want to your documents sorted by a property, right now the sort key needs to be part of the index itself. In an e-commerce environment, that's really annoying as the index size becomes prohibitively massive.

500 products sorted into
100 categories (100 indexes of 500 products)
Not terrible but quite sizeable

quickly becomes
 
10,000 products sorted into 
1,000 categories (1000 indexes of 10,000 products)
Absolutely massive (tens of gb)

**Describe the solution you'd like**
Ideally I would like to implement a sort on a property of my documents at query time, ideally, after the search module has actually retrieved the search results dragonfly would sort the limited subset based on my field (which in my case is a property of an object on my document which is an integer), I understand this will not be as performant as the indexed sort, but the performance comes at a significantly reduced memory overhead.

**Describe alternatives you've considered**
Right now, I make a new index per category, which is blowing out memory usage but far less than an index with 100's of sortable fields.

**Comment by dranikpg** [comment]
Hi. Thanks for trying out our new features!

We'll try to add this feature in the nearest feature, probably even in the next version. As you already pointed out, the performance will be much worse, because the values need to be fetched from the entries. But as long as your queries don't match thousands of items, it should be acceptable

**Comment by claridgicus** [comment]
@dranikpg 

Not to dictate how you build this feature
could I potentially declare these sort fields as their own mini index, so that sorting is done on the subsidiary index?

Atleast then I wouldn't see such a massive hit to the performance of the query.

**Comment by romange** [comment]
@claridgicus ,  we are going to implement sort during the query time, i.e. according to your original suggestion:

```
Ideally I would like to implement a sort on a property of my documents at query time, ideally, after the search module has actually retrieved the search results dragonfly would sort the limited subset based on my field (which in my case is a property of an object on my document which is an integer)
```

if we build a precomputed index  (secondary or not) , it will take space, which will bring us to the original issue you had with 1000 indices taking too much space.

**Comment by dranikpg** [comment]
> if we build a precomputed index (secondary or not) , it will take space, which will bring us to the original issue you had with 1000 indices taking too much space.

I think I understand which suggestion he has in mind. If a document is matched by multiple indices, each index independently builds it's sort index. For example, if a product belongs to 10 different indices, then it's price will be stored 10 times in the sort index. Which is wasteful...

The issue with building a unified sort index is that each sub-index has it's own document numbering, around which the sort index is built. So two indices can only share one sort index if they have the same set of documents.

If they have the same set of documents, they can be actually united into one index 🙂 

@claridgicus 

Is is true that you currently use multiple index key prefixes (i.e. FT.CREATE PREFIX..., we don't support it but it can be added easily 😅 ) ? So that all your indices might share documents, but they're all not the same. Or is there any other specific reason why you need 1000 indices instead of keeping the category as a tag (or array of tags) inside one big index?

**Comment by claridgicus** [comment]
@dranikpg I think you've got exactly my issue.

Right now so you understand my usecase

I have a multitennanted redis cluster (in 4 regions)

For each Tennant 

I load in JSON format
- Every Collection the Tennant has
- Every Product the Tennant has
- A view of every product (for some application logic where I implode many references into a composite)

I build
A "Search" index which is what I use for my Full Text Search requirements
Many "Collection" indexes (this is my problem) which reference their own sort orders

I have many, many, many prefixes

I want an index to partition my tenants data at the boundary of their prefix so I'm not indexing everyone's stuff everywhere.
