### ISSUE TITLE
Dragonfly is persistent, but not persistent if the amount of keys is larger than a specific value

### ISSUE THREAD

**Issue by simon-liebehenschel** [dragonflydb/dragonfly#2445]
### Describe the bug

:ok_hand: Dragonfly persists data on a Docker container restart e.g. if I have a few keys.

:heavy_minus_sign:  Dragonfly is not persistent on a Docker container restart If the amount of keys is larger than 59000000 (59 millions).

### To Reproduce

1. Start Dragonfly via Docker Compose.
2. Create 59 000 000 key or more.
3. Stop all Docker containers.
4. Restart the container. No data!

### Expected behavior

Persist any amount of keys or document the default limits and workarounds.

### Environment
 - OS: `Debian GNU/Linux 12 (bookworm)`
 - Kernel: `Linux 22dfcb82393c 6.6.11-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:23:27 UTC 2024 x86_64 GNU/Linux`
 - Containerized? Docker Compose
 - Dragonfly Version: `docker.dragonflydb.io/dragonflydb/dragonfly:v1.13.0`

### Workarounds

Manually call the `SAVE` command.

**Comment by romange** [comment]
what's your docker compose config @AIGeneratedUsername ?

**Comment by romange** [comment]
we do not have of course limits on number of keys. Could it be that when you stop containers, docker waits K seconds and if dragonfly does not save your data in time, it just forcefully kills it?

**Comment by romange** [comment]
@AIGeneratedUsername  you can save periodically using [`--snapshot_cron` ](https://www.dragonflydb.io/docs/managing-dragonfly/backups#the-snapshot_cron-flag) flag. I also suggest increasing `proactor_threads` if possible, because it will increase dragonfly performance and the saving pace.Finally, check out this option:
https://docs.docker.com/compose/compose-file/compose-file-v2/#stop_grace_period - this probably will help you.
