### ISSUE TITLE
Snapshoting big values increases memory usage

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2585]
**Describe the bug**
When creating a snapshot we serialize entire bucket entry by entry and push them to channel. If the entry key/value is huge this will impact immediately our memory usage.

We should limit the memory used for serialization.

**Comment by romange** [comment]
I would like to add, that for convoluted case of a single huge entry, just limiting serialization memory usage won't be enough, since we still need to serialise at least a single entry somehow. 

Another comment: I suspect we do not attribute all all the RSS usage in this case. I saw that with a 30GB single entry,
our RSS was ~100GB, while memory stats attributed data as 30GB, serialization as 30GB and other 30GB were missing.

**Comment by kostasrim** [comment]
I am closing this as this is fixed since we now send the data in batches/chunks
