### ISSUE TITLE
Release musl builds for CentOS 7

### ISSUE THREAD

**Issue by recursionbane** [dragonflydb/dragonfly#263]
**Did you search GitHub Issues and GitHub Discussions First?**
Yes

**Is your feature request related to a problem? Please describe.**
Attempting to run on CentOS 7 yields GLIBC errors

**Describe the solution you'd like**
Release musl builds so newer versions of GLIBC are not required. A performance hit is expected for this convenience.

**Describe alternatives you've considered**
Currently using Redis standalone binary.

**Additional context**
N/A

**Comment by romange** [comment]
CentOS is 10 years old. Does it even have kernel 5.10 or later?

**Comment by recursionbane** [comment]
Kernel is 4.14

Yes, it's an old OS, but it is the OS of choice for large enterprise compute farms.

**Comment by romange** [comment]
In 2 years' time, this kernel will reach EOL.
We currently do not support kernels older than 5.10, since Dragonfly relies on io_uring instead of epoll. 
So glibc is not the most significant barrier here. We might consider supporting older kernels if an interesting enterprise design emerges. wink wink.
