### ISSUE TITLE
persistent node ids in cluster mode

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#2643]

**Comment by chakaz** [comment]
Some background on this issue:
1. We need unique IDs for Dragonfly masters to support partial replication. This eliminates potential collisions when a replica connects to a different, or restarted, Dragonfly server
2. We also need unique IDs for Dragonfly cluster nodes, so that they know which part of the config is assigned to them. In theory we could have used IP/port, but external/internal IPs make this complicated. I'm not sure it's worth giving up on, as it might simplify things.

Anyway, currently we use the same ID for the above 2 (unrelated) requirements.
This issue is about being able to have a persistent ID for _cluster_ purposes. So my questions are:
1. Is this persistent ID a flag (`--node_id=X`)?
2. If not, is it saved in the RDB file? If so, what about nodes that do use `--dbfilename=`?
3. Is this ID different from the replication ID?
My personal preference is to have a `--node_id=X`, which if unset randomizes a string like we do today. Replication will use the same ID, which means users have to be careful about setting this ID and switching replicas between masters with the same ID (but why would that even be a scenario?)

**Comment by romange** [comment]
@ashotland  to chip in. Also related to #2636
1. do we need node id for cluster i.e. master and replica nodes for the same shard will have different ids, 
2. or we should set a shard id, i.e. master/slaves will share the same shard id, and slaves will indeed accept it upon replication together with cluster config. 

I do not think that replication should use the same id as master_id for replication if that's what @chakaz  means - see #2636 why we always want a random id for the replication.
