### ISSUE TITLE
crash in migrate flow

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#2703]
Before migrating a connection we should join on connection-dispatch fiber.

see here for faulty run: https://github.com/dragonflydb/dragonfly/actions/runs/8203214807/job/22435576161#step:12:703

cc @adiholden 

```
30002➜ Check failure stack trace: ***
30002➜ 12:46:07.572312 32135 dragonfly_connection.cc:1411] Check failed: !dispatch_fb_.IsJoinable() 
30002➜ Check failure stack trace: ***
30002➜    @     0x556e17f1dea0  google::LogMessage::Fail()
30002➜    @     0x556e17f1dea0  google::LogMessage::Fail()
30002➜    @     0x556e17f25093  google::LogMessage::SendToLog()
30002➜    @     0x556e17f25093  google::LogMessage::SendToLog()
30002➜    @     0x556e17f1d857  google::LogMessage::Flush()
30002➜    @     0x556e17f1d857  google::LogMessage::Flush()
30002➜    @     0x556e17f1f1df  google::LogMessageFatal::~LogMessageFatal()
30002➜    @     0x556e17f1f1df  google::LogMessageFatal::~LogMessageFatal()
30002➜    @     0x556e17aa863f  facade::Connection::Migrate()
30002➜    @     0x556e17aa863f  facade::Connection::Migrate()
30002➜    @     0x556e178e4f7b  dfly::ClusterFamily::DflyMigrateFlow()
30002➜    @     0x556e178e4f7b  dfly::ClusterFamily::DflyMigrateFlow()
30002➜    @     0x556e178ea352  dfly::ClusterFamily::DflyMigrate()
30002➜    @     0x556e178ea352  dfly::ClusterFamily::DflyMigrate()
30002➜    @     0x556e179da32f  dfly::CommandId::Invoke()
30002➜    @     0x556e179da32f  dfly::CommandId::Invoke()
30002➜    @     0x556e177c986c  dfly::Service::InvokeCmd()
30002➜    @     0x556e177c986c  dfly::Service::InvokeCmd()
30002➜    @     0x556e177ce3b7  dfly::Service::DispatchCommand()
30002➜    @     0x556e177ce3b7  dfly::Service::DispatchCommand()
30002➜    @     0x556e17aaa059  facade::Connection::DispatchCommand()
30002➜    @     0x556e17aaa059  facade::Connection::DispatchCommand()
30002➜    @     0x556e17aaa350  facade::Connection::ParseRedis()
30002➜    @     0x556e17aaa350  facade::Connection::ParseRedis()
30002➜    @     0x556e17aad21a  facade::Connection::ConnectionFlow()
30002➜    @     0x556e17aad21a  facade::Connection::ConnectionFlow()
30002➜    @     0x556e17aae26f  facade::Connection::HandleRequests()
30002➜    @     0x556e17aae26f  facade::Connection::HandleRequests()
30002➜    @     0x556e17ec8e2d  util::ListenerInterface::RunSingleConnection()
30002➜    @     0x556e17ec8e2d  util::ListenerInterface::RunSingleConnection()
```

**Comment by BorysTheDev** [comment]
This crash happened because of a connection-blocking operation. When we do connection-blocking we prevent execute new commands so this bug affects other functionalities too: replication, CLIENT PAUSE command, DFLYCLUSTER CONFIG command, and cluster migration process. 
One of the options to solve it is to mark internal connections (replication, migration) as non-blocking.

**Comment by chakaz** [comment]
Here's a proposal: how about we never block the admin port, if exists?
With this, we can instruct users to connect replicas and do cluster migration via the admin port, but never issue "data related" commands via it.
It's easy to implement and "clean" in that we don't need to identify internal connections or annotate a subset of commands. It also sounds like a good idea regardless - to not block admin commands.

**Comment by adiholden** [comment]
If I understand correctly
The problem:
Running client pause will block all internal connections between master and replica / cluster nodes
The solution by Shahar:
Do cluster migration / replication over admin port
The changes need to support this solution:
1. Instruct users to use only admin port for replication
2. In cluster mode add admin port to config so that when cluster migration start we will use admin port for migrating data.
3. In client pause implementation we will pause only non admin port commands this is by changing dispatch tracker to traverse only non admin port listener and in dispatch command call AwaitPauseState only if the connection is not on admin port. 

Is this right?

**Comment by chakaz** [comment]
Yes, except:

> In cluster mode add admin port to config so that when cluster migration start we will use admin port for migrating data.

If by "add" you mean "use" then yes, but otherwise there aren't code changes required to cluster config (we don't need 2 ports, etc)

**Comment by BorysTheDev** [comment]
@adiholden @chakaz Not only client PAUSE, but all places where we use DispatchTrecker for example cluster config and migration finalization also do connection blocking

**Comment by adiholden** [comment]
> Yes, except:
> 
> > In cluster mode add admin port to config so that when cluster migration start we will use admin port for migrating data.
> 
> If by "add" you mean "use" then yes, but otherwise there aren't code changes required to cluster config (we don't need 2 ports, etc)

Cluster config is used for seting cluster configuration in node so that we can answer to client CLUSTER commands, to those commands we should not reply with the admin port

**Comment by chakaz** [comment]
Of course, I'm only saying that the existing cluster design doesn't require any changes.
