### ISSUE TITLE
tps

### ISSUE THREAD

**Issue by githubzhangfei** [dragonflydb/dragonfly#2802]
About the tps problem of dragonflydb, my program needs 10,000 concurrent queries per second. The pipeline query method I use requires 100 queries per request. In other words, the tps of dragonflydb is 10,000 times 100 get times. We want 10,000 pieces of data to be returned in 10 milliseconds.

**Comment by githubzhangfei** [comment]
What kind of configuration can support. And I need to make the application highly available. Using cluster mode does not know whether pipeline queries are supported or not. As far as I know redis clusters don't support pipelining

**Comment by ashotland** [comment]
Hi @githubzhangfei 

I think Dragonfly should be able to cope with the throughput and latency numbers you mentioned.
You can refer to https://github.com/dragonflydb/dragonfly#benchmarks to get a sense of the hardware required 

For HA:
If you are on K8S you can use https://www.dragonflydb.io/docs/managing-dragonfly/operator/installation
Otherwise, Dragonfly is redis sentinel compatible so you can use https://redis.io/docs/management/sentinel/
