### ISSUE TITLE
Memcached flags loses during load from snapshot

### ISSUE THREAD

**Issue by sbkoto** [dragonflydb/dragonfly#3134]
not fixed on 1.19.0

```
set item 4 3600 4
test
STORED
get item
VALUE item 4 4
test
END

```

after reload dragonfly and load from snapshot: 
```
get item
VALUE item 0 4
test
END
```

_Originally posted by @sbkoto in https://github.com/dragonflydb/dragonfly/issues/1758#issuecomment-2149633624_

**Comment by romange** [comment]
definition of done - rdb_test reloads the snapshot file with mcflags.

**Comment by chakaz** [comment]
Thanks for filing this issue, @sbkoto. We plan to work on this soon.

Some more context:
* memcached allows adding an integer flag to entries. In this case, the flag's value is `4`
* This metadata does not exist in Redis, so accessing it is only possible via the memcached API
* We currently do not have support for this in `rdb_save.cc` and `rdb_load.cc`. We should add it, using a custom opcode (like we have for the `STICKY` bit today), because it's not supported nativly in RDB format
* We _do_ have support for this for stable sync. So a replica _will_ accept changes for the flag. But it will not get the original value in full sync, for the same reason it is not saved to files.
* IMHO, in addition to `rdb_test`, we should also add replication test to make sure this information is sent to replicas
