### ISSUE TITLE
Integrate FakeRedis tests as github action for better coverage 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#3515]
https://github.com/cunla/fakeredis-py

**Comment by cunla** [comment]
I can do it.

**Comment by romange** [comment]
Thanks!

**Comment by cunla** [comment]
Hi, I have started working on this project on the fakeredis repository.

Meanwhile, please review whether the logic and the results make sense:
- Process: Different sets of tests are run against Dragonfly and against Fakeredis, and all html results are combined to a GHA artifact - see [here](https://github.com/cunla/fakeredis-py/actions/runs/10393435202) example run and download the results artifact (scroll to the bottom of the page to see the artifact to download).
- Results: I had to [disable some tests (using `@pytest.mark.unsupported_server_types("dragonfly")`](https://github.com/cunla/fakeredis-py/pull/318/files) due to unsupported commands. However:
  - I added a `# TODO` comment where I believe the test should pass but it causes an issue.


If you are good with the process/how the results are presented look (GHA artifact with HTML files) - I will create a PR to add it here next week.

**Comment by romange** [comment]
nm, found this article: https://eswarayerra.medium.com/publishing-coverage-report-html-report-on-github-pages-f5d29de47cfb
seems to be possible indeed.
