### ISSUE TITLE
Memory tracking for JSON data type

### ISSUE THREAD

**Issue by kostasrim** [dragonflydb/dragonfly#3661]
Our tracking for JSON is buggy. First no matter the size of the json will always report `16 bytes` per object. Second we don't track the internal memory used by Json objects. 

The fix is simple but the `pmr` in `jsoncons` library is buggy as well.

I am creating this issue to:

1. Track the bug/issue reported on jsoncons lib
2. Once (1) is resolved merge my pr

**Comment by kostasrim** [comment]
https://github.com/danielaparker/jsoncons/issues/539

**Comment by romange** [comment]
@kostasrim  if you happen to know how to fix the issue, we do not need to wait for Daniel to fix it in his repo - we use our own fork - https://github.com/dragonflydb/jsoncons/tree/Dragonfly
which also btw is very much behind jsoncons.

1. It could be that their latest release already fixes the issue
2. we could also potentially patch Dragonfly with the fix. But if the fix is complicated - no need to spend too much time on it and we will patiently wait on it a few more months.

**Comment by kostasrim** [comment]
1. I did not know we use our own `fork`
2. Yes I think I can patch this fairly fast (which I will then send as a PR to them).
