### ISSUE TITLE
Enable tx inline execution when snapshoting/journaling step 1 - transaction acquire key lock on OPTIMISTIC_EXECUTION

### ISSUE THREAD

**Issue by adiholden** [dragonflydb/dragonfly#3841]
Today we do not acquire key lock when transaction runs inline (OPTIMISTIC_EXECUTION)
If we preemp when running the command callback execution this can lead to a bug
We need this change to enable inline schedualing while replicating/snapshoting/using tiering which can cause preemption in callback execution

**Comment by kostasrim** [comment]
uh I remember I had this discussion with @romange while I was working on big value serialization

IMO I always thought that inline transactions do not require to acquire a lock for the keys since they are "fast to execute" but preemptions do cause issues. 

Also in the past, we did require locks even for inline transactions so this PR is as simple as reverting those changes.

I do wonder what's the overhead of acquiring those locks. I guess there should be none, since they are "logical locks". Maybe worth benchmarking. (again I don't remember the code there so I will take a look and maybe add one if it's worth it -- whcich IMO I don't think that's the case)

**Comment by adiholden** [comment]
The code evolved alot I dont think you can just revert the changes, and I dont think benchmarking for this change this should not have impact on performance

**Comment by romange** [comment]
Yeah, I recently optimized the data structures there (we use fingerprints now), so I guess it should have very negligible impact.

**Comment by kostasrim** [comment]
@romange yep +1
