### ISSUE TITLE
Document `pipeline_buffer_limit`/`pipeline_queue_limit` and, optionally, add log or raise an error when a pipeline hits the limit

### ISSUE THREAD

**Issue by alessio-locatelli** [dragonflydb/dragonfly#3999]
**Is your feature request related to a problem? Please describe.**

This is a follow-up for https://github.com/dragonflydb/dragonfly/discussions/3997

Currently, it can be tricky for a user to see why executing large pipelines stopped working after `v1.20.0`.

**Describe the solution you'd like**

- [ ] Mention `pipeline_queue_limit` and `pipeline_buffer_limit` on the https://www.dragonflydb.io/docs/managing-dragonfly/known-limitations webpage.

- [ ] Optionally, one of the following:
   - Return an error to the client.
   - Write ERROR or WARNING logs.

**Describe alternatives you've considered**

A user can limit the pipeline size, but a user will not know about this problem until their code hangs forever, and then they find this issue.

**Comment by romange** [comment]
Regarding the core issue.

When we write into socket synchronously (during the reply), and it blocks, there is not much we can do, because using timeouts on each write is highly inefficient. We could write asynchronously - but then we must keep the pending buffer alive until the request finishes. This would be equivalent to Client Output Buffer (COB) in valkey. 

In general,the best practice is of course not to use pipelines of huge sizes - it's not efficient and puts additional memory pressure on both the client and the server.
