### ISSUE TITLE
Snapshot cron argument format parsing issue in config file

### ISSUE THREAD

**Issue by Niennienzz** [dragonflydb/dragonfly#4023]
**Description**

It seems that the `--snapshot_cron` argument format is not parsed consistently in the config file. Specifically, there appears to be a discrepancy in whether a space after the `=` sign is required for the cron format to work as expected.

---

**Steps to Reproduce**

1. Set `--snapshot_cron` in the config file without a space after the `=` sign, e.g., `--snapshot_cron=*/15 * * * *`
Result -> **No snapshots are created.**

2. Set `--snapshot_cron` with a space after the `=` sign, e.g., `--snapshot_cron= */15 * * * *`
Result -> Snapshots are created as expected.

3. Notably, other cron formats, e.g., `--snapshot_cron=15 * * * *` without a leading `*`
Result -> Snapshots are created as expected.

---

**Expected Behavior**

Passing a valid crontab should work properly with or without spaces. There should be no edge cases for parsing.

**Comment by ioannidesalex** [comment]
OS: Ubuntu 22.04
Kernel: 5.15.0-124
Containerized?: No, Bare Metal, amd64
Dragonfly Version: 1.24.0

**Comment by BorysTheDev** [comment]
Hi @ioannidesalex unfortunately I don't think that we can fix this issue because without quotes it's not understandable where the end of this flag's argument is due to a lot of spaces.

I can just recommend using quotes ( --snapshot_cron="*/15 * * * *" )

**Comment by BorysTheDev** [comment]
I will check one more time with quotes

**Comment by BorysTheDev** [comment]
@ioannidesalex I've investigated the question deeper and:

1. --snapshot_cron=*/15 * * * *    - parsed correctly because * is a list of files in the directory, but */15 is invalid value for snapshot_cron
2. --snapshot_cron= */15 * * * *    - parsed correctly too for the same reason, but the result is the empty/default value
3. --snapshot_cron="*/15 * * * *"    - parsed correctly because it's the only way how it should work
4. --snapshot_cron= "*/15 * * * *"    - parsed correctly because space means empty value and  "*/15 * * * *" is the next argument

for argument parsing we use the absl_flags library and the only way to change behavior is by using another library, but I don't see any point in doing this
