### ISSUE TITLE
Error in Logs: COMMAND DOCS failed with reason: syntax error

### ISSUE THREAD

**Issue by wernermorgenstern** [dragonflydb/dragonfly#4200]
**Describe the bug**
I see an error in the Logs for DragonFly.
```
 W20241126 16:40:26.354447    14 main_service.cc:1459]  COMMAND DOCS failed with reason: syntax error
 ```

**To Reproduce**
Not sure how to reproduce it.  It shows up occasionally

**Expected behavior**
Explain what the error means, and if I need to be concerned about it.

**Environment (please complete the following information):**
 - Containerized?: EKS Kubernetes
 - Dragonfly Version: 1.24.0

**Comment by chakaz** [comment]
Thanks @wernermorgenstern for reporting this!
This actually means that the client you're using issued the `COMMAND` command (I know, it's confusing, but there is such a command) with a sub-command `DOCS`.

See [`COMMAND`](https://valkey.io/commands/command/) and [`COMMAND DOCS`](https://valkey.io/commands/command-docs/).

Unfortunately this sub-command is not yet supported in Dragonfly. As long as everything works on your side you can safely ignore this. Otherwise, keep this issue open and we'll prioritize this among our other compatibility tasks.
