### ISSUE TITLE
Implement subset of RediSearch

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#431]
Quoting a nodejs user, they want to create an index like this:
```ts
import { SchemaFieldTypes } from 'redis';
import { redis } from '..';

redis.ft
    .CREATE(
        'index:channels',
        {
            '$.id': {
                type: SchemaFieldTypes.TEXT,
                AS: 'id',
                SORTABLE: true,
            },
            '$.guildId': {
                type: SchemaFieldTypes.TEXT,
                AS: 'guildId',
                SORTABLE: true,
            },
         
            '$.position': {
                type: SchemaFieldTypes.NUMERIC as any,
                AS: 'position',
                SORTABLE: true,
            },
        },
        {
            ON: 'JSON',
            PREFIX: 'channels',
        }
    )
    .catch(() => null);
```
and then be able to query it like this:

```ts
await utils.redisSearch('index:channels', `@guildId:${id}`);
```

note - we do not need a full-text search, stemming, query rewrite and other language related features. 
Instead this task is about formal, semi-structured querying that will provide lots of value for folks that use RedisJson.

The task is a super task that should be broken down into smaller sub-projects:
1) Auto indexing (FT.CREATE)
2) Building a query AST tree with all the operators we support.
3) Executing a query without query plan optimizations.

**Comment by iko1** [comment]
I think you meant writing in the title RedisSearch and not JsonSearch.

**Comment by romange** [comment]
You are right, but since the subset of functionality I want to focus on is within JSON , this mistake makes sense 😄

**Comment by romange** [comment]
Could be a great MVP for query part

**Comment by sirfz** [comment]
I'm not a RediSearch user (yet) but have been very interested in it recently as it seems to be exactly what I need for my use case.

In particular, the vector similarity search can be a killer feature to have in dragonfly.

In general, RediSearch seems to be an all around great feature and having it in dragonfly, in my opinion, would bring lots of adoption. Just my 2 cents

**Comment by dwzkit** [comment]
My project heavily utilizes the combination of RediSearch and RediJSON, requiring roughly 100-300 FT.SEARCH commands per second in 2-3 million records to obtain results that meet various conditions. Additionally, the TTL of my 200-300 million records is only around 180-480 seconds, meaning the load on both writing and reading (FT.SEARCH, with the requirement that the average query result returns within 300ms) from the Redis cluster is quite high. As a result, I had to build a Redis cluster to meet these demands, which makes the overall maintenance cost relatively high. Therefore, I'm looking for an architecture that can achieve this effect at a lower cost. If DragonFlyDB can provide full-text search capabilities similar to RediSearch and RediJSON, I would be willing to give it a try.

**Comment by romange** [comment]
Can you provide an example for a typical query that you send? Do you need word stemming, multiple languages support in full text search?

**Comment by dwzkit** [comment]
> Can you provide an example for a typical query that you send? Do you need word stemming, multiple languages support in full text search?

I currently do not need to use stemming because my project is mainly to help users match mobile phone numbers related to their favorite numbers. Since the matching is all about numeric strings, even if it is a Chinese project, I don't need to use Chinese, just numbers and English letters. Here is my search example:
`FT.SEARCH tm '@hitMassRuleId:lastABABAB|anyABCDABCD|lastAAABBB|lastAABBCC|lastABCABC|lastABCDDBCAXXX|anyAABBCC|anyAAABBB|lastAAAAB|lastAAAAA|anyABCDEF|anyAAAAA|lastAABBB|lastABCDABDCXXX|lastABCDBACD|lastABCDBACDXXX|lastABCDDCBA|lastAAAA|lastABCDACBDXXX|lastABBA|lastABBCBB|lastABCDABDC|anyAAAA|lastAABB|anyABABAB|anyABCABC|anyAAAAB|midAAAA|anyAAABB|anyABBCBB|lastABABtu368|anyAABBB|lastABBB|lastABABtu613|lastABAB|lastABABtu850|midBAAA|lastABCD|midAAAB|lastAABCC|midAABB|lastBrithYear758799|lastAAAB|midABCD|midABAB|any888|any666|lastAABAAXXX|lastABCCBAXX|anyABAB|anyABABtu368|anyBrithYear758799|anyABBA|anyAABB|anyABABtu850|anyABABtu613|lastABB|anyABCD|lastXAXAXAXA|lastXAXAXA|lastABAC|lastAXAXAX|anyAAA|head1889|lastABACAD|anyABBCDD|lastAXAXAXAX @ttlInSecond:[1683364311 +inf] @providerCode:jyxf @status:1 @preOrderTime:[-inf (1683364009] @touchCode:P00000035328 @province:beijing @city:beijing ' LIMIT 0 0`

**Comment by romange** [comment]
Looks like a structured search, do not see here any full text-search
requirements but maybe i am missing something.

**Comment by sirfz** [comment]
In my case, fulltext search is the least interesting feature of RediSearch. I'm more interested in running queries like:

```
FT.SEARCH items-index "(@brand:xxx @model:xxx)=>[KNN 10 @vector $vector as score]" ...
```

which translates to something like: for all items that match brand `xxx` and model `xxx`, get me the top 10 closest items to the given $vector. Stemming/normalization could be useful for the attributes filter I guess but the power is more about searching multiple attributes and returning other attriubutes/columns (and of course the vector similarity search is great).

**Comment by dwzkit** [comment]
In Redis Cluster mode, I am unable to simultaneously call FT.SEARCH and JSON.SET operations within a single Lua script, because doing so involves different hosts and different slots, and cross-slot combination operations are not supported. This is one of the areas where I think Redis Cluster mode is not as perfect as it could be.

**Comment by romange** [comment]
@sirfz  hey can you DM me on discord? I am curious to hear more about your usecase.

**Comment by romange** [comment]
@sirfz  @dwzkit we will have an experimental version of `FT.SEARCH` in v1.10 (next release).
Would you like to try it out?

**Comment by dwzkit** [comment]
> @sirfz @dwzkit we will have an experimental version of `FT.SEARCH` in v1.10 (next release). Would you like to try it out?

I'm sorry, I've been busy with other projects recently and may not have time to experiment for the next two months.

**Comment by chakaz** [comment]
Since we use dedicated issues for the various missing features / bugs, can we close this issue now? @dranikpg

**Comment by romange** [comment]
Yeah, the feature has been released long time ago.
