### ISSUE TITLE
Benchmarks against other stores like Skytable/Aerospike/SSDB?

### ISSUE THREAD

**Issue by firedupmike** [dragonflydb/dragonfly#58]
This looks really interesting! Have you considered benchmarking against Skytable (which has [very impressive benchmarks](https://github.com/ohsayan/sky-benches) surpassing both KeyDB and Redis by a large factor) or Aerospike (which also has [very impressive benchmarks](https://aerospike.com/lp/five-signs-you-have-outgrown-redis/) against Redis)? I have been following all the projects lately and am just curious.

PS: I know Aerospike is more mature but Skytable is a pretty recent project

**Comment by firedupmike** [comment]
Hmm, just to note neither Skytable nor Aerospike are compatible with Redis

**Comment by romange** [comment]
I have not heard of Skytable before. By a first look of it - it's not redis compatible store. 
It's not really a hard problem to introduce a highly efficient backend today that can handle single key operations in its K-V store . I actually released [midi-redis](https://github.com/romange/midi-redis) a while ago that does just that - it's just a few thousands lines of code and most of it is parsing.

The real problem is how you guarantee atomicity and strict serializability for multi-key operations. This is where the difficulty is

**Comment by romange** [comment]
> Hmm, just to note neither Skytable nor Aerospike are compatible with Redis

exactly.

**Comment by firedupmike** [comment]
Yeah, Aerospike is completely different (no commands and all) but Skytable does have a bunch of Redis/KeyDB actions

**Comment by firedupmike** [comment]
Thanks for the info! Closing :)

**Comment by firedupmike** [comment]
Just to note, Aerospike does have multi K/V operations and Skytable seems to have it on their roadmap. We can revisit this in the future maybe
