### ISSUE TITLE
expose `/typez` page 

### ISSUE THREAD

**Issue by romange** [dragonflydb/dragonfly#712]
This html table page should show types distribution.

motivation: when we load an rdb file we sometimes want to know what it has and it's impossible to scan large database without knowing which types are stored there.

**Comment by romange** [comment]
Can also be done as a subcommand `DEBUG TYPEZ` which returns an array "string, 5, set, 6, zset 16" etc.

**Comment by devangjhabakh** [comment]
@romange Hey Roman! I'm working on the ticket and I realize there may be multiple ways to approach solving this. I can either
1. Modify the load function such that it stores a counter of each `type` loaded from the RDB file, maybe we can store this counter in the `DebugCmd` struct itself.
2. Re-read the RDB file and count the `type`s.
I realize that one flaw that arises from using method 2 is that, in the event the RDB file is modified/deleted, it will print inconsistent results _if_ the RDB file has been stored in memory already.
Also, if I am missing something (like a data structure that is holding this information already), please correct me.

**Comment by romange** [comment]
Good questions. As you pointed out (2) will be awkward so I think we should follow (1).
I would suggest even better approach. I want to know the distribution of types in the database unrelated to where they come from - rdb file or by a command like "set", "zadd" etc.
So I think the best place to track the insertion event is in `DbSlice::AddOrFind2` and we can store the distribution inside 
`DbTable`, along `DbTableStats stats` member. 
Note, that I want to avoid putting those histograms inside DbTableStats because I do not think we want to merge them from all databases and all threads every time we call `info` command.

**Comment by devangjhabakh** [comment]
Hi Roman! I've made a fairly simple Draft PR at #809, please let me know if you think it's making progress in the right direction? I've tested with very simple cases and it works, so if you think this is the right kind of progress, I will continue to make a more robust solution. Thanks!

**Comment by chakaz** [comment]
Some questions:
1. After looking around, I came to conclude that `DbSlice::AddOrFind2()` actually isn't a good place to update the statistics. The reason is that, to my understanding, we actually don't have the object (value) at hand, and so we can't know what type it is. Right?
1a. I found `DbSlice::PostUpdate()`, which seems to be called with the actual value for strings and sets, but not for new lists (oddly, it is called for existing lists). Maybe that's an unrelated bug?
2. Thinking more about updates, I'm not sure what's the intended behavior. Let's say the user sets `x` to be of type `string`, then updates it to be of type `set`. What should be the counts following that? string:1, set:1? string:0, set:1?
2a. Same goes to deletions: set `x` to type `string` and then delete it, should we update the counts?
2b. Similarly, if the user pushes `N` times to the same list, I *think* that the count should be `1` rather than `N`.
Initially I thought that `PostUpdate()` (when `existing==false`) is a good place to update the counts, but that wouldn't solve updates.
3. The most accurate, though expensive, way to implement this would be to do online. By that I mean that every time `DEBUG TYPEZ` is issued, we'll go over the entire DB. I imagine that this is a no-go performance-wise, right? I just want to make sure, because this would solve all of the above complexities.

**Comment by romange** [comment]
Good questions.

1. We should have up-to-date count of types without scanning the whole database. And yes, we should take into account deletions as well.
2. We count per entry in the *main database* so 1+ items in a list count as one.
3. It's not possible to convert a string into a set without going through deletion first.

It's quite possible that we need to hook into each of the families and introduce an additional hook function similar to PostUpdate that is called UponAddition or something - I did not dive in 🤷🏼

**Comment by chakaz** [comment]
@romange I tried another approach for implementing this feature, see https://github.com/dragonflydb/dragonfly/commit/793634483c475ccad58e68b31c6f340b873d6368

I do think it's a better implementation (tracking is done in 1 place, and is therefore less error prone), but I still need some help here :)
The new test *does not* pass at the moment, as it shows ~5,000 objects of type STRING are "unaccounted for". This even happens in an empty database (i.e. when the test runs `debug typez` before adding anything, even when running the test with `--gtest_filter=SingleThreadDflyEngineTest.Typez` so no other tests will interfere).
I can see that these allocations come from `Bucket` within `dash_internal.h`. Is there a way to "know" how many such allocations happen to subtract that at runtime? The numbers don't add up for me (`kTotalBuckets` should be 66, but evidently it's more).
Also, while at it, how can I know how many keys exist in the database? Currently I look at `DbTableStats::inline_keys`, but I suspect it's not accounting for non-inline(?) keys.

Thanks!
