### ISSUE TITLE
[QUESTION]metrics for memory usage

### ISSUE THREAD

**Issue by quiver** [dragonflydb/dragonfly#98]
I have a question regarding memory usage in Dragonfly.

https://github.com/dragonflydb/dragonfly/blob/main/doc/dashtable.md#populate-single-threaded

In this page, you compare memory usage between Redis and Dragonfly.

> When looking at Redis6 "info memory" stats, you can see that used_memory_overhead field equals to 1.0GB. That means that out of 1.73GB bytes allocated, a whooping 1.0GB is used for the metadata. For small data use-cases the cost of metadata in Redis is larger than the data itself.

At Redis, `used_memory` = `used_memory_overhead`(metadata) + `used_memory_dataset`(data itself).

What are Dragonfly's counterparts for `used_memory_overhead` and `used_memory_dataset` respectively?

Best regards.

**Comment by romange** [comment]
It's a great question. Unfortunately, this categorization is harder to apply in Dragonfly. 

Dragonfly uses Small-Object Optimization, i.e. sometimes its table space is used to embed objects and sometimes it's just a table space and then it's an "overhead". I try to measure object space and table space separately but due to various technical reasons it does not work for all data types. It works for strings though.

so if you run  "debug populate 1000", you can see that `info memory` returns `inline_keys:10000` which means all keys were stored inline inside the table. `object_used_memory:0` which means that no object allocations were made, so objects have also been stored inline.  Therefore the only contributing factor is `table_used_memory:1069040`  (on my machine) which is the allocated memory for tables but they contain inline both key and the values. Now tell me how you consider it - is it an overhead? a dataset? 

When comparing DF to Redis I usually use `used_memory_human` or `used_memory_rss_human` just to compare apples to apples.

**Comment by quiver** [comment]
Hi @romange, thank you for your answer.

The background to my question is that from the doc it's clear that DF implements a better data datastructure than Redis and I thought that apple-to-apple metrics exist.

But from your answer, there are no such metrics(DF might store data inline).

I will take your advice and use `used_memory_human` for apple-to-apple comparisons.

Mark this closed.
